name: Setup pnpm & Node
description: Setup pnpm, Node.js and install dependencies
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.29.3

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash

    - uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: 'main'
