packages:
  - 'apps/*'
  - 'libs/**/*'

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - 'esbuild'
  - 'less'
  - 'lmdb'
  - 'msgpackr-extract'
  - 'nx'
  - 'prisma'
  - 'unrs-resolver'
